default: &default
  database: <%= "ubuntu_#{Rails.env}" %>
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production_or_staging: &production_or_staging
  username: ubuntu
  password: <%= ENV['UBUNTU_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  <<: *production_or_staging
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  <<: *production_or_staging
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
