default: &default
  database: <%= "ubuntu_#{Rails.env}" %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  
development:
  <<: *default

test:
  <<: *default

production_or_staging: &production_or_staging
  username: ubuntu
  password: <%= ENV['UBUNTU_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  <<: *production_or_staging

production:
  <<: *default
  <<: *production_or_staging
