common: &common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>


development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common
  
production:
  <<: *common

